package by.javaguru.core.types;

public enum OrderStatus {
    CREATED,
    PRODUCT_RESERVED,
    PRODUCT_RESERVATION_FAILED,
    PAYMENT_PROCESSED,
    PAYMENT_FAILED,
    APPROVED,
    PRODUCT_RESERVATION_CANCELLED,
    REJECTED
}
