server:
  port: 8080

spring:
  application:
    name: orders-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      group-id: orders-ms
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: by.javaguru.core.*
    streams:
      properties:
        # commit.interval.ms: 100
        processing.guarantee: exactly_once_v2

orders:
  events:
    topic:
      name: orders-events
  commands:
    topic:
      name: orders-commands

products:
  commands:
    topic:
      name: products-commands
  events:
    topic:
      name: products-events

payments:
  commands:
    topic:
      name: payments-commands
  events:
    topic:
      name: payments-events

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
