server:
  port: 8081

spring:
  application:
    name: products-service
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
        allow.auto.create.topics: false
    consumer:
      group-id: products-ms
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: by.javaguru.core.*
        allow.auto.create.topics: false

products:
  commands:
    topic:
      name: products-commands
  events:
    topic:
      name: products-events

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
